<a href="https://colab.research.google.com/github/mequanent/Bioinformatics-Project/blob/main/hw1_110761504.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Clone the repository first using the following command
!npx degit https://github.com/mequanent/Bioinformatics-Project -f

npx: installed 1 in 2.273s
> destination directory is not empty. Using --force, continuing
> cloned mequanent/Bioinformatics-Project#HEAD


In [22]:
import numpy as np
np.set_printoptions(suppress=True) # Suppress displaying the scientific notation

file = open("mut.txt", "r")
lines = file.readlines()[2:] # remove the first two lines
mut = []
for line in lines:
  line = line[1:].strip().split() # remove the letters from left and the spaces
  mut.append(line)
file.close()
mut = np.array(mut).astype(int) # convert the string array into numpy array of integers
print('mut size: ', mut.shape) # confirm if we get the right matrix size from the text
mut = np.true_divide(mut, 10000) # Change the four digit values into values between 0 & 1
print(np.round(mut, 4))

print('PAMx')
# ************* PAMx Function *********************
def pam(x):
  PAMx = mut
  for i in range(2, x+1):
    #PAMx = np.matmul(mut, PAMx)
    PAMx = np.matmul(PAMx, mut)
    #PAMx = np.rint(PAMx * 100)
    #PAMx = PAMx * 100
  return np.rint(PAMx * 100).astype(int)
# ************* End of the PAMx Function ***********
PAM250 = pam(250)
print(PAM250)

mut size:  (20, 20)
[[0.9867 0.0002 0.0009 0.001  0.0003 0.0008 0.0017 0.0021 0.0002 0.0006
  0.0004 0.0002 0.0006 0.0002 0.0022 0.0035 0.0032 0.     0.0002 0.0018]
 [0.0001 0.9913 0.0001 0.     0.0001 0.001  0.     0.     0.001  0.0003
  0.0001 0.0019 0.0004 0.0001 0.0004 0.0006 0.0001 0.0008 0.     0.0001]
 [0.0004 0.0001 0.9822 0.0036 0.     0.0004 0.0006 0.0006 0.0021 0.0003
  0.0001 0.0013 0.     0.0001 0.0002 0.002  0.0009 0.0001 0.0004 0.0001]
 [0.0006 0.     0.0042 0.9859 0.     0.0006 0.0053 0.0006 0.0004 0.0001
  0.     0.0003 0.     0.     0.0001 0.0005 0.0003 0.     0.     0.0001]
 [0.0001 0.0001 0.     0.     0.9973 0.     0.     0.     0.0001 0.0001
  0.     0.     0.     0.     0.0001 0.0005 0.0001 0.     0.0003 0.0002]
 [0.0003 0.0009 0.0004 0.0005 0.     0.9876 0.0027 0.0001 0.0023 0.0001
  0.0003 0.0006 0.0004 0.     0.0006 0.0002 0.0002 0.     0.     0.0001]
 [0.001  0.     0.0007 0.0056 0.     0.0035 0.9865 0.0004 0.0002 0.0003
  0.0001 0.0004 0.0001 0.     0.0003 0

In [24]:
"A, R, N, D, C, Q, E, G, H, I, L, K, M, F, P, S, T, W, Y, V "
"Ala, Arg, Asn, Asp, Cys, Gln, Glu, Gly, His, Ile, Leu, Lys, Met, Phe, Pro, Ser, Thr, Trp, Tyr, Val"
"fi = 0.087, 0.041, 0.040, 0.047, 0.033, 0.038, 0.050, 0.089, 0.034, 0.037, 0.085, 0.081, 0.015, 0.040, 0.051, 0.070, 0.058, 0.010, 0.030, 0.065"
"Mj = 100, 65, 134, 106, 20, 93, 102, 49, 66, 96, 40, 56, 94, 41, 56, 120, 97, 18, 41, 74"
fi = [0.087, 0.041, 0.040, 0.047, 0.033, 0.038, 0.050, 0.089, 0.034, 0.037, 0.085, 0.081, 0.015, 0.040, 0.051, 0.070, 0.058, 0.010, 0.030, 0.065]
mj = [100, 65, 134, 106, 20, 93, 102, 49, 66, 96, 40, 56, 94, 41, 56, 120, 97, 18, 41, 74]

In [35]:
Rij = []
for i in range(20):
  Rij.append(PAM250[i] / fi[i] / 100)
Rij

[array([1.49425287, 0.68965517, 1.03448276, 1.03448276, 0.57471264,
        0.91954023, 1.03448276, 1.37931034, 0.68965517, 0.91954023,
        0.68965517, 0.8045977 , 0.8045977 , 0.45977011, 1.37931034,
        1.26436782, 1.37931034, 0.22988506, 0.45977011, 1.03448276]),
 array([0.73170732, 3.90243902, 0.97560976, 0.73170732, 0.48780488,
        1.2195122 , 0.73170732, 0.48780488, 1.46341463, 0.73170732,
        0.48780488, 2.19512195, 0.97560976, 0.48780488, 0.97560976,
        0.97560976, 0.73170732, 1.70731707, 0.24390244, 0.48780488]),
 array([1.  , 1.  , 1.5 , 1.75, 0.5 , 1.25, 1.5 , 1.25, 1.5 , 0.75, 0.5 ,
        1.25, 0.75, 0.5 , 1.  , 1.25, 1.25, 0.5 , 0.75, 0.75]),
 array([1.06382979, 0.63829787, 1.70212766, 2.34042553, 0.21276596,
        1.4893617 , 2.12765957, 1.27659574, 1.06382979, 0.63829787,
        0.42553191, 1.06382979, 0.63829787, 0.21276596, 0.85106383,
        1.06382979, 1.06382979, 0.21276596, 0.42553191, 0.63829787]),
 array([ 0.60606061,  0.60606061,  0.303

In [34]:
m = np.array([[1., 0], [2, 3]])
res = np.log2(m, out=np.zeros_like(m), where=(m!=0))
res

array([[0.       , 0.       ],
       [1.       , 1.5849625]])

In [40]:
#Sij = np.log10(Rij) * 10 
Sij = np.log10(Rij, out=np.zeros_like(Rij), where=(Rij!=0))
Sij = np.rint(Sij * 10).astype(int)
#print(Sij)
Sij

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log10
  


array([[                   2,                   -2,                    0,
                           0,                   -2,                    0,
                           0,                    1,                   -2,
                           0,                   -2,                   -1,
                          -1,                   -3,                    1,
                           1,                    1,                   -6,
                          -3,                    0],
       [                  -1,                    6,                    0,
                          -1,                   -3,                    1,
                          -1,                   -3,                    2,
                          -1,                   -3,                    3,
                           0,                   -3,                    0,
                           0,                   -1,                    2,
                          -6,                   -3],
      

Questions:
1. Are we going to use the contents in the matrices like mut by dividing into 100 to change into a percentage? Dividing by 100 gives very small values than expected.