<a href="https://colab.research.google.com/github/mequanent/Bioinformatics-Project/blob/main/hw1_110761504.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Clone the repository first using the following command
!npx degit https://github.com/mequanent/Bioinformatics-Project -f

npx: installed 1 in 2.796s
> destination directory is not empty. Using --force, continuing
> cloned mequanent/Bioinformatics-Project#HEAD


In [3]:
import numpy as np
file = open("mut.txt", "r")
lines = file.readlines()[2:] # remove the first two lines
mut = []
for line in lines:
  line = line[1:].strip().split() # remove the letters from left and the spaces
  mut.append(line)
file.close()
mut = np.array(mut).astype(int) # convert the string array into numpy array of integers
print('mut size: ', mut.shape) # confirm if we get the right matrix size from the text
#mut = np.true_divide(mut,100) # Dividing leads PAM250 to overfloaw
print(mut)

print('PAMx')
def pam(x):
  PAMx = mut
  for i in range(2, x+1):
    PAMx = np.matmul(mut, PAMx)
  return PAMx
PAM250 = pam(2)
print(PAM250)

mut size:  (20, 20)
[[9867    2    9   10    3    8   17   21    2    6    4    2    6    2
    22   35   32    0    2   18]
 [   1 9913    1    0    1   10    0    0   10    3    1   19    4    1
     4    6    1    8    0    1]
 [   4    1 9822   36    0    4    6    6   21    3    1   13    0    1
     2   20    9    1    4    1]
 [   6    0   42 9859    0    6   53    6    4    1    0    3    0    0
     1    5    3    0    0    1]
 [   1    1    0    0 9973    0    0    0    1    1    0    0    0    0
     1    5    1    0    3    2]
 [   3    9    4    5    0 9876   27    1   23    1    3    6    4    0
     6    2    2    0    0    1]
 [  10    0    7   56    0   35 9865    4    2    3    1    4    1    0
     3    4    2    0    1    2]
 [  21    1   12   11    1    3    7 9935    1    0    1    2    1    1
     3   21    3    0    0    5]
 [   1    8   18    3    1   20    1    0 9912    0    1    1    0    2
     3    1    1    1    4    1]
 [   2    2    3    1    2    1    

In [4]:
"A, R, N, D, C, Q, E, G, H, I, L, K, M, F, P, S, T, W, Y, V "
"Ala, Arg, Asn, Asp, Cys, Gln, Glu, Gly, His, Ile, Leu, Lys, Met, Phe, Pro, Ser, Thr, Trp, Tyr, Val"
"fi = 0.087, 0.041, 0.040, 0.047, 0.033, 0.038, 0.050, 0.089, 0.034, 0.037, 0.085, 0.081, 0.015, 0.040, 0.051, 0.070, 0.058, 0.010, 0.030, 0.065"
"Mj = 100, 65, 134, 106, 20, 93, 102, 49, 66, 96, 40, 56, 94, 41, 56, 120, 97, 18, 41, 74"
fi = [0.087, 0.041, 0.040, 0.047, 0.033, 0.038, 0.050, 0.089, 0.034, 0.037, 0.085, 0.081, 0.015, 0.040, 0.051, 0.070, 0.058, 0.010, 0.030, 0.065]
mj = [100, 65, 134, 106, 20, 93, 102, 49, 66, 96, 40, 56, 94, 41, 56, 120, 97, 18, 41, 74]



In [5]:
PAM250[0]

array([97360669,    40374,   179818,   199244,    60056,   159272,
         336801,   416764,    40347,   120153,    79790,    40538,
         119484,    39981,   436480,   691891,   633537,      228,
          39936,   356688])

In [6]:
Rij = []
for i in range(20):
  Rij.append(PAM250[i]/fi[i])
Rij

[array([1.11908815e+09, 4.64068966e+05, 2.06687356e+06, 2.29016092e+06,
        6.90298851e+05, 1.83071264e+06, 3.87127586e+06, 4.79039080e+06,
        4.63758621e+05, 1.38106897e+06, 9.17126437e+05, 4.65954023e+05,
        1.37337931e+06, 4.59551724e+05, 5.01701149e+06, 7.95277011e+06,
        7.28203448e+06, 2.62068966e+03, 4.59034483e+05, 4.09986207e+06]),
 array([4.91024390e+05, 2.39679424e+09, 5.04341463e+05, 7.17073171e+03,
        4.87292683e+05, 4.83921951e+06, 1.20731707e+04, 4.53658537e+03,
        4.84351220e+06, 1.45329268e+06, 4.88195122e+05, 9.19778049e+06,
        1.94414634e+06, 4.86634146e+05, 1.94246341e+06, 2.89902439e+06,
        4.96390244e+05, 3.88195122e+06, 3.04878049e+03, 4.88609756e+05]),
 array([2.00072500e+06, 5.17350000e+05, 2.41187232e+09, 1.77325250e+07,
        7.30000000e+03, 1.99970000e+06, 3.01292500e+06, 2.98107500e+06,
        1.03699000e+07, 1.48627500e+06, 4.98350000e+05, 6.42912500e+06,
        1.38500000e+04, 5.00400000e+05, 1.00442500e+06, 9.85

In [8]:
Sij = np.log10(Rij) * 10 
Sij

array([[90.48864297, 56.66582526, 63.1531391 , 63.59865999, 58.3903715 ,
        62.62620181, 65.8785412 , 66.80370945, 56.66291996, 61.40215366,
        59.62429212, 56.68343066, 61.37790501, 56.623344  , 67.00445096,
        69.00518429, 68.62252731, 34.18415594, 56.61845311, 66.12769246],
       [56.91103065, 93.79630753, 57.02724674, 38.55563474, 56.8778989 ,
        66.84775323, 40.81821342, 36.56729087, 66.85160398, 61.62353087,
        56.88593436, 69.63683041, 62.88728952, 56.87202579, 62.88352848,
        64.62251869, 56.95823237, 65.89050074, 34.84126156, 56.88962134],
       [63.01187399, 57.13784453, 93.82354314, 72.48770581, 38.6332286 ,
        63.00964847, 64.78988321, 64.74372902, 70.15774568, 61.72099173,
        56.97534463, 68.0815187 , 41.41449773, 56.99317301, 60.01917514,
        69.93627983, 66.49536866, 56.97708721, 62.97065303, 57.02322811],
       [64.05059209, 38.42449895, 72.45662272, 93.15588946, 32.91689969,
        64.09447466, 73.47432996, 64.05113746, 6

Questions:
1. What value of lambda are we going to use?
2. Do we need to manually copy the values of Aij or is there any method to relate Aij with mut.txt?
3. Are we going to use the contents in the matrices like mut by dividing into 100 to change into a percentage?
4. Are we going to find the PAM250 from mut.txt and use that PAM250 as M(Mij) values to compute Rij = Mij/fi?