<a href="https://colab.research.google.com/github/mequanent/Bioinformatics-Project/blob/main/hw1_110761504.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Clone the repository first using the following command
!npx degit https://github.com/mequanent/Bioinformatics-Project -f

npx: installed 1 in 2.271s
> destination directory is not empty. Using --force, continuing
> cloned mequanent/Bioinformatics-Project#HEAD


In [6]:
import numpy as np
file = open("mut.txt", "r")
lines = file.readlines()[2:] # remove the first two lines
mut = []
for line in lines:
  line = line[1:].strip().split() # remove the letters from left and the spaces
  mut.append(line)
file.close()
mut = np.array(mut).astype(int) # convert the string array into numpy array of integers
print('mut size: ', mut.shape) # confirm if we get the right matrix size from the text
#mut = np.true_divide(mut,100) # Dividing leads PAM250 to overfloaw
print(mut)

print('PAMx')
# ************* PAMx Function *********************
def pam(x):
  PAMx = mut
  for i in range(2, x+1):
    PAMx = np.matmul(mut, PAMx)
  return PAMx
# ************* End of the PAMx Function ***********
PAM250 = pam(250)
print(PAM250)

mut size:  (20, 20)
[[9867    2    9   10    3    8   17   21    2    6    4    2    6    2
    22   35   32    0    2   18]
 [   1 9913    1    0    1   10    0    0   10    3    1   19    4    1
     4    6    1    8    0    1]
 [   4    1 9822   36    0    4    6    6   21    3    1   13    0    1
     2   20    9    1    4    1]
 [   6    0   42 9859    0    6   53    6    4    1    0    3    0    0
     1    5    3    0    0    1]
 [   1    1    0    0 9973    0    0    0    1    1    0    0    0    0
     1    5    1    0    3    2]
 [   3    9    4    5    0 9876   27    1   23    1    3    6    4    0
     6    2    2    0    0    1]
 [  10    0    7   56    0   35 9865    4    2    3    1    4    1    0
     3    4    2    0    1    2]
 [  21    1   12   11    1    3    7 9935    1    0    1    2    1    1
     3   21    3    0    0    5]
 [   1    8   18    3    1   20    1    0 9912    0    1    1    0    2
     3    1    1    1    4    1]
 [   2    2    3    1    2    1    

In [9]:
"A, R, N, D, C, Q, E, G, H, I, L, K, M, F, P, S, T, W, Y, V "
"Ala, Arg, Asn, Asp, Cys, Gln, Glu, Gly, His, Ile, Leu, Lys, Met, Phe, Pro, Ser, Thr, Trp, Tyr, Val"
"fi = 0.087, 0.041, 0.040, 0.047, 0.033, 0.038, 0.050, 0.089, 0.034, 0.037, 0.085, 0.081, 0.015, 0.040, 0.051, 0.070, 0.058, 0.010, 0.030, 0.065"
"Mj = 100, 65, 134, 106, 20, 93, 102, 49, 66, 96, 40, 56, 94, 41, 56, 120, 97, 18, 41, 74"
fi = [0.087, 0.041, 0.040, 0.047, 0.033, 0.038, 0.050, 0.089, 0.034, 0.037, 0.085, 0.081, 0.015, 0.040, 0.051, 0.070, 0.058, 0.010, 0.030, 0.065]
mj = [100, 65, 134, 106, 20, 93, 102, 49, 66, 96, 40, 56, 94, 41, 56, 120, 97, 18, 41, 74]

In [10]:
Rij = []
for i in range(20):
  Rij.append(PAM250[i]/fi[i])
Rij

[array([-5.51946119e+19,  8.73263673e+19, -9.03324510e+19, -3.69297108e+19,
         4.62895512e+19,  3.48871307e+19, -5.50901965e+17, -6.90920821e+19,
        -2.34210134e+19, -6.94566265e+19, -4.21399811e+19, -6.65644074e+19,
         8.44069915e+19,  7.88864865e+19, -7.37392147e+19,  2.00508481e+19,
        -8.00975364e+19,  5.90645270e+18,  8.02126840e+19, -9.46240581e+18]),
 array([-2.09141893e+20,  1.81066793e+20, -8.92147465e+19, -1.24251638e+20,
         9.17873522e+19, -1.83988232e+20, -6.43913438e+17, -1.42509839e+20,
         7.95213772e+19,  2.17400434e+20,  7.86836855e+19,  5.17395923e+19,
         1.31318253e+20, -5.46586284e+19,  1.93940334e+20,  6.41359053e+19,
        -2.98462989e+19, -9.23650996e+19, -1.38167368e+20,  2.10776430e+20]),
 array([-1.92189346e+20, -4.92258585e+19,  9.61158173e+19, -2.01462121e+20,
         3.05318732e+19, -7.25145983e+19, -1.08525233e+20, -1.95959713e+20,
        -2.19461584e+20, -1.49035692e+19, -2.27743507e+20,  1.12873842e+20,
        

In [11]:
Sij = np.log10(Rij) * 10 
Sij

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log10
  """Entry point for launching an IPython kernel.


array([[         nan, 199.41145394,          nan,          nan,
        196.6548297 , 195.42665252,          nan,          nan,
                 nan,          nan,          nan,          nan,
        199.26378421, 198.97002614,          nan, 193.02132746,
                 nan, 187.7132673 , 199.04243049,          nan],
       [         nan, 202.57838809,          nan,          nan,
        199.62782842,          nan,          nan,          nan,
        199.00483893, 203.37260406, 198.95884694, 197.13823002,
        201.18325096,          nan, 202.87668139, 198.07101229,
                 nan,          nan,          nan, 203.23822044],
       [         nan,          nan, 199.82794863,          nan,
        194.8475345 ,          nan,          nan,          nan,
                 nan,          nan,          nan, 200.52593307,
        203.56430309,          nan, 201.17143101, 200.52392541,
                 nan,          nan,          nan, 199.05622373],
       [         nan,          nan, 1

Questions:
1. Are we going to use the contents in the matrices like mut by dividing into 100 to change into a percentage? Dividing by 100 gives very small values than expected.